#! Used when internal-encryption is set to "true"
---
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: knative-serving-certs
  namespace: knative-serving
spec:
  delegations:
    - secretName: knative-serving-certs
      targetNamespaces:
      - "*"
